name: CI

on: push
name: Build SODA Dashboard
jobs:
  build:

    runs-on: runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04]
        node-version: [11]

    steps:
    - uses: actions/checkout@v1
    
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y nginx make
      env:
        CI: true
    - name: Build the dashboard
      run: make
      env:
        CI: true
    - name: Clean up after install
      run: make clean
      env:
        CI: true
    
